-- central neovim configuration (loaded from init.lua via: require('config'))

-- core editor options and ui
require("config.options")
require("config.colors")
require("config.keymaps")

-- plugins (each plugin has its own module under lua/plugins)
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.gitsigns")
require("plugins.diffview")
require("plugins.treesitter")
require("plugins.comment")
require("plugins.autopairs")
require("plugins.cmp")
require("plugins.lsp")
require("plugins.conform")
require("plugins.trouble")
require("plugins.floaterm")
require("plugins.lazygit")
require("plugins.dap")
